---

- hosts: localhost

  tasks:

  - include_vars: /docroot/.container.yml

  ### setup cron jobs ###
  - name: setup cron jobs
    cron:
      name={{ item.key }}
      minute={{ item.value.minute }}
      hour={{ item.value.hour }}
      day={{ item.value.day }}
      month={{ item.value.month }}
      weekday={{ item.value.weekday }}
      job={{ item.value.command }}
    with_dict: "{{ cron_jobs }}"
    when: cron_jobs is defined

  ### execute post-deployment commands ###
  - name: execute deployment commands
    shell: "{{ item.value.command }} >> /var/log/commands.log"
    args:
      executable: /bin/bash
      chdir: "{{ item.value.directory }}"
    with_dict: "{{ deployment_commands }}"
    when: deployment_commands is defined
