---

- hosts: localhost

  tasks:

  - name: download project build
    get_url:
      url=https://s3-{{ lookup('env','AWS_REGION') }}.amazonaws.com/{{ lookup('env','S3_URL') }}
      dest=/tmp/build.tar.gz

  - name: extract project build
    unarchive:
      src=/tmp/build.tar.gz
      dest=/
      copy=no
      owner=apache
      group=apache

  - name: remove project build archive
    file:
      path=/tmp/build.tar.gz
      state=absent

  - name: symlink file directory
    file:
      src=/assets
      dest=/public/sites/default/files
      owner=apache
      group=apache
      state=link

  - name: set permissions on /assets
    file:
      path=/assets
      owner=apache
      group=apache
      recurse=true
      state=directory
  - name: set permissions on /private
    file:
      path=/private
      owner=apache
      group=apache
      recurse=true
      state=directory

  - name: include inventory file
    include_vars: /.container.yml

  - name: configure postfix
    template:
      src=/tmp/{{ item }}
      dest=/etc/postfix/{{ item }}
    with_items:
      - main.cf
      - sasl_passwd
  
  - name: create postfix hashmap database
    shell: postmap hash:/etc/postfix/sasl_passwd

  - name: remove sasl_passwd file
    file:
      path=/etc/postfix/sasl_passwd
      state=absent
  
  - name: set permission on postix db file
    file:
      path=/etc/postfix/sasl_passwd.db
      owner=root
      group=root
      mode=0600
  
  - name: configure postfix cert directories
    shell: postconf -e 'smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt'
  
  - name: start postfix
    shell: postfix start
  
  - name: setup ssh system keys
    shell: ssh-keygen -A
  
  - name: start ssh server
    shell: /usr/sbin/sshd

  - name: setup cron jobs
    cron:
      name={{ item.key }}
      minute={{ item.value.minute }}
      hour={{ item.value.hour }}
      day={{ item.value.day }}
      month={{ item.value.month }}
      weekday={{ item.value.weekday }}
      job={{ item.value.command }}
    with_dict: "{{ cron_jobs }}"
    when: cron_jobs is defined

  - name: execute deployment commands
    shell: "{{ item.value.command }} >> /var/log/commands.log"
    args:
      executable: /bin/bash
      chdir: "{{ item.value.directory }}"
    with_dict: "{{ deployment_commands }}"
    when: deployment_commands is defined
